name: Test Bit Lane Archive
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize Bit
        uses: bit-tasks/init@v1
        with:
            ws-dir: 'test-data'
      - name: Bit Pull Request
        uses: bit-tasks/pull-request@main
      - name: Bit Lane Cleanup
        uses: bit-tasks/lane-cleanup@main
        with:
            archive: 'true'
      - name: Bit Lanes After Cleanup
        run: cd test-data && bit lane list --details
